version: '3.3'

services:
  sandbox:
    image: sandbox:1.0.0
    hostname: sandbox
    container_name: sandbox
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "59022:22"
    volumes:
      - st_data:/etc
      - st_home:/home

volumes:
  st_data:
  st_home: